Checkout.TestAPI/Controllers/CardTransactionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using Checkout.TestAPI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace Checkout.TestAPI.Controllers
{
    public class CardTransactionsController : Controller
    {
        private readonly ILogger<CardTransactionsController> _logger;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IConfiguration _configuration;

        public CardTransactionsController(ILogger<CardTransactionsController> logger, IHttpContextAccessor httpContextAccessor, IConfiguration configuration)
        {
            _logger = logger;
            _httpContextAccessor = httpContextAccessor;
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            TransactionModel model = new TransactionModel();
            return View(model);
        }


        public async Task<IActionResult> GetData(TransactionModel model)
        {
            TempData["APIKey"] = model.APIKey;
            List<PaymentResponse> paymentResponses = new List<PaymentResponse>();

            var token = "";
            using (var httpClient = new HttpClient())
            {
                var tokenRequest = new APIModeModel() { apiKey = model.APIKey };
                StringContent content = new StringContent(JsonConvert.SerializeObject(tokenRequest), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync($"{_configuration.GetSection("appSettings")["PaymentAPI"]}/Token", content))
                {
                    token = await response.Content.ReadAsStringAsync();
                }
            }

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);


                using (var response = await httpClient.GetAsync($"{_configuration.GetSection("appSettings")["PaymentAPI"]}/CardTransaction/GetPayments/20"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    paymentResponses = JsonConvert.DeserializeObject<List<PaymentResponse>>(apiResponse);
                }
            }
            if (paymentResponses != null)
            {
                model.Transactions = paymentResponses;

            }

            return View("Index", model);
        }

        public async Task<IActionResult> Detail(string id)
        {
            var APIKey =Convert.ToString( TempData["APIKey"]);
            var token = "";
            using (var httpClient = new HttpClient())
            {
                var tokenRequest = new APIModeModel() { apiKey = APIKey };
                StringContent content = new StringContent(JsonConvert.SerializeObject(tokenRequest), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync($"{_configuration.GetSection("appSettings")["PaymentAPI"]}/Token", content))
                {
                    token = await response.Content.ReadAsStringAsync();
                }
            }

            CardTransactionResponse cardTransactionResponse = null;
            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);


                using (var response = await httpClient.GetAsync($"{_configuration.GetSection("appSettings")["PaymentAPI"]}/CardTransaction/Detail/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    cardTransactionResponse  = JsonConvert.DeserializeObject<CardTransactionResponse>(apiResponse);
                }
            }
             
            return View("detail", cardTransactionResponse);
        }
    }
}

Checkout.TestAPI/Views/CardTransactions/Detail.cshtml
@model CardTransactionResponse
<div class="container">


    <div class="row h-100">
        <div class="col-sm-12 my-auto">
            <div class="box-shadow card card-block w-50 mx-auto" style="background-color:ghostwhite">
                <div style="padding:50px;">
                    

                    <div class="alert alert-light"><span class="glyphicon-inf" />@Model.Description</div>
                    <div class=" box-shadow ">
                        <div class="padding50 border-dark" style="background-color:white;">
                            <div class="row">
                                <div class="col">Amount :</div>
                                <div class="col"><strong> @Model.Amount @Model.Currency </strong></div>
                            </div>
                            <div class="row">
                                <div class="col">Name on Card:</div>
                                <div class="col">@Model.HolderName</div>
                            </div>
                            <div class="row">
                                <div class="col">Credit card number:</div>
                                <div class="col">@Model.CardNumber</div>
                            </div>
                              
                        </div>


                    </div>
                </div>
                 
            </div>

        </div>
    </div>

    <div class="d-block row" style="clear:both">
        <div style="margin-bottom:5px;padding:10px;" class="d-inline-flex"><a href="/CardTransactions"><< Transaction List</a></div>
    </div>

</div>

Checkout.TestAPI/Views/CardTransactions/Index.cshtml
@model TransactionModel


<div class="container">
    <h2>List of payments</h2>


    <form method="post">
        <div class="row">
            <div class="form-group col">
                <label asp-for="APIKey">API Call Mode</label>
                <select class="form-control" asp-for="APIKey" asp-items="@Model.GetAPIKeys()"></select>
            </div>
            <div class="form-group col">
                <input type="submit" name="ShowData" value="Show Data" class="btn btn-primary" asp-action="GetData" />
            </div>
        </div>
    </form>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">TransctionCode</th>
                <th scope="col">Date created</th>
                <th scope="col">Amount</th>
                <th scope="col">Status</th>

                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>

            @foreach (PaymentResponse payment in Model.Transactions)
            {
                <tr>
                    <td>@payment.TransctionCode</td>
                    <td>@payment.CreateDateTime</td>
                    <td>@payment.Amount.ToString()</td>
                    <td>@payment.PaymentStatus</td>

                    <td>
                        @if (payment.PaymentStatus == "Open")
                        {
                            <a href="@payment.CheckoutUrl" class="btn btn-outline-secondary" target="_blank">Pay</a>
                        }

                        @if (payment.PaymentStatus == "Paid")
                        {
                            <form method="post" asp-controller="CardTransactions" asp-action="Detail" asp-route-id="@payment.TransctionCode" >
                                <input type="submit" name="Detail" value="Detail" class="btn btn-outline-secondary" />
                            </form>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>


</div>